# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@3rd-gcc
      with:
          kernel-url: https://github.com/Mrcl1450/kernel_xiaomi_cepheus
          kernel-branch: lxc
          config: cepheus_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          other-gcc32-url: https://github.com/kdrag0n/proton-clang
          other-gcc32-branch: master
          other-gcc64-url: https://github.com/kdrag0n/proton-clang
          other-gcc64-branch: master
          android-version: 12
          aosp-clang-version: r416183b1
          anykernel3: true
          lxc: true
          lxc-patch: false
          nethunter: true
          nethunter-patch: false
          disable-lto: true
          extra-cmd: LLVM=1 CROSS_COMPILE=aarch64-linux-gnu- AR=llvm-ar LD=ld.lld NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip
